services:
  # Serviço do Front-end (Nginx)
  frontend:
    build: ./Front-end
    ports:
      - "8080:80"
    volumes:
      - ./Front-end:/usr/share/nginx/html

  # Serviço do Back-end (FastAPI)
  backend:
    build: ./Back-end
    ports:
      - "8000:8000"
    environment:
      DB_HOST: database
      DB_USER: dev_user
      DB_PASSWORD: devpassword
      DB_NAME: wagegap_db
      DB_PORT: 3306
    depends_on:
      - database
    volumes:
      - ./Back-end:/app

  # Serviço do Banco de Dados (MySQL 8.0)
  database:
    image: mysql:8.0
    container_name: wagegap_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wagegap_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: devpassword
    ports:
      - "3307:3306"
    volumes:
      - ./Back-end/database/init.sql:/docker-entrypoint-initdb.d/init.sql