# 1. Usa a imagem oficial e leve do Nginx baseada em Alpine Linux
FROM nginx:alpine

# 2. Copia todos os arquivos estáticos da pasta Front-end para o diretório padrão do Nginx
COPY . /usr/share/nginx/html

# 3. Expõe a porta 80 do container
EXPOSE 80